[server]
headless = true             # Wajib untuk deployment
maxUploadSize = 50         # Turunkan ke 50MB karena data time series biasanya tidak terlalu besar
enableCORS = false         # Nonaktifkan CORS untuk performa
enableXsrfProtection = false  # Nonaktifkan XSRF untuk performa

[cache]
persist = true            # Pertahankan cache
max_entries = 50          # Turunkan jumlah cache entries
ttl = 1800               # Cache timeout 30 menit (dalam detik)

[runner]
# Batasi penggunaan memori untuk mencegah OOM
memoryLimit = 1.0        # Turunkan ke 1GB
# Batasi jumlah proses
maxNumberProcesses = 1    # Batasi ke 1 proses
# Timeout untuk proses lama
processTimeout = 180     # 3 menit timeout

[theme]
primaryColor = "#FF4B4B"  # Warna tema (opsional)
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[logger]
level = "info"           # Level logging untuk debugging
messageFormat = "%(asctime)s %(message)s"
